version: "3"
services:
    web:
        container_name: 'dotnet'
        restart: 'always'
        working_dir: /app
        build: 
            context: ./bin/dotnet
        ports:
            - "8000:80"
            - "5000:5000"
            - "5001:5001"
        depends_on:
            - db
        volumes:
            - ./app:/app
        #command: "dotnet run"
        #entrypoint: dotnet run
        entrypoint: "dotnet watch run --urls http://0.0.0.0:5000"


    db:
        container_name: 'db'
        restart: 'always'
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y" 
