version: "3"
services:
    web:
        build: 
            context: ./bin/dotnet
        ports:
            - "80:80"
        depends_on:
            - db
        volumes:
            - /app:/app
        expose:
            - "80"

    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y" 
