version: "3"
services:
    web:
        container_name: 'dotnet'
        restart: 'always'
        working_dir: /app
        build: 
            context: ./bin/dotnet
        ports:
            - "${PORT}:5000"
        depends_on:
            - db
        volumes:
            - ${APP_DIR}:/app
        entrypoint: "dotnet watch run --urls http://0.0.0.0:5000"


    db:
        container_name: 'db'
        restart: 'always'
        image: "mcr.microsoft.com/mssql/server"
        volumes:
            - ${DATA_DIR}:/var/opt/mssql/data/
        environment:
            SA_PASSWORD: "${SA_PASSWORD}"
            ACCEPT_EULA: "Y" 
